apiVersion: v1
kind: Service
metadata:
  name: rms-bff
  namespace: rms
  labels:
    app: rms-bff
spec:
  selector:
    app: rms-bff
  type: LoadBalancer # O type "LoadBalancer" torna o service acessível fora do cluster, em localhost, no Kubernetes do Docker Desktop
  ports:
    - protocol: TCP
      port: 3000 # Porta na máquina local
      targetPort: 3000 # Porta do Pod