apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: rms
spec:
  provider: aws
  secretObjects:
    - secretName: db-bff-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: mercadopago-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: ACCESS_TOKEN_MERCADOPAGO
          key: ACCESS_TOKEN_MERCADOPAGO
        - objectName: USER_ID_MERCADOPAGO
          key: USER_ID_MERCADOPAGO
        - objectName: EXTERNAL_POS_ID_MERCADOPAGO
          key: EXTERNAL_POS_ID_MERCADOPAGO
        - objectName: WEBHOOK_URL_MERCADOPAGO
          key: WEBHOOK_URL_MERCADOPAGO
        - objectName: IDEMPOTENCY_KEY_MERCADOPAGO
          key: IDEMPOTENCY_KEY_MERCADOPAGO
    - secretName: cognito-secret # Nome do Secret que será montado automaticamente contendo os segredos do AWS Secrets Manager
      type: Opaque
      data:
        - objectName: COGNITO_USER_POOL_ID
          key: COGNITO_USER_POOL_ID
        - objectName: COGNITO_CLIENT_ID
          key: COGNITO_CLIENT_ID
  parameters:
    # Informe abaixo no campo objectName os nomes dos Segredos do AWS Secrets Manager que deseja acessar.
    # Certifique-se de que as Keys declaradas abaixo existem e estão preenchidas na AWS, caso contrário receberá o erro "Failed to fetch secret from all regions"
    objects: |
      - objectName: "prod/RMS/Postgresql"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
      - objectName: "prod/RMS/MercadoPago"
        objectType: "secretsmanager"
        jmesPath:
          - path: "ACCESS_TOKEN_MERCADOPAGO"
            objectAlias: "ACCESS_TOKEN_MERCADOPAGO"
          - path: "USER_ID_MERCADOPAGO"
            objectAlias: "USER_ID_MERCADOPAGO"
          - path: "EXTERNAL_POS_ID_MERCADOPAGO"
            objectAlias: "EXTERNAL_POS_ID_MERCADOPAGO"
          - path: "WEBHOOK_URL_MERCADOPAGO"
            objectAlias: "WEBHOOK_URL_MERCADOPAGO"
          - path: "IDEMPOTENCY_KEY_MERCADOPAGO"
            objectAlias: "IDEMPOTENCY_KEY_MERCADOPAGO"
      - objectName: "prod/RMS/Cognito"
        objectType: "secretsmanager"
        jmesPath:
          - path: "COGNITO_USER_POOL_ID"
            objectAlias: "COGNITO_USER_POOL_ID"
          - path: "COGNITO_CLIENT_ID"
            objectAlias: "COGNITO_CLIENT_ID"
